# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20170505.0.0"
  config.vm.provision :shell, path: "bootstrap/run.sh"
  config.vm.network :forwarded_port, guest:4848, host:14848
  config.vm.network :forwarded_port, guest:3306, host:13306
end
