# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.box_version = "20170505.0.0"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "bootstrap/playbook.yml"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end 

  config.vm.network :forwarded_port, guest:8088, host:18088
  #config.vm.network :forwarded_port, guest:3306, host:13306
end
